@TmsApi_HostAddress = http://localhost:5148

GET {{TmsApi_HostAddress}}/weatherforecast/
Accept: application/json

###
GET http://localhost:5148/api/assessments/results
X-Training-User: Rita
Accept: application/json
##
curl -i https://localhost:5148/api/v1/courses

curl -i https://localhost:5148/api/v2/courses

curl -i -X POST https://localhost:5148/api/v2/transcripts 
